default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  database: bloobloom_development

test:
  <<: *default
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: localhost
  database:  bloobloom_test

production:
  <<: *default
  database:  bloobloom_production
  username: app
  password: <%= ENV["BLOOBLOOM_DATABASE_PASSWORD"] %>